export const languageOptions = [
  { code: "en_gb", flag: "🇬🇧", label: "English", htmlLang: "en-GB" },
  { code: "en_us", flag: "🇺🇸", label: "English", htmlLang: "en-US" },
  { code: "es", flag: "🇪🇸", label: "Español", htmlLang: "es" },
  { code: "zh_cn", flag: "🇨🇳", label: "中文 (中国)", htmlLang: "zh-CN" },
  { code: "ar", flag: "🇸🇦", label: "العربية", htmlLang: "ar", rtl: true },
  { code: "fr", flag: "🇫🇷", label: "Français", htmlLang: "fr" },
  { code: "de", flag: "🇩🇪", label: "Deutsch", htmlLang: "de" },
  { code: "tr", flag: "🇹🇷", label: "Türkçe", htmlLang: "tr" },
  { code: "it", flag: "🇮🇹", label: "Italiano", htmlLang: "it" },
  { code: "pl", flag: "🇵🇱", label: "Polski", htmlLang: "pl" },
  { code: "vi", flag: "🇻🇳", label: "Tiếng Việt", htmlLang: "vi" },
  { code: "ja", flag: "🇯🇵", label: "日本語", htmlLang: "ja" },
  { code: "pt_br", flag: "🇧🇷", label: "Português", htmlLang: "pt-BR" },
]

const packs = {
  es: {
    "Partner Fleet Console": "Consola de flota de socios",
    "Partner fleet console for all assigned nodes": "Consola de flota para todos los nodos asignados",
    "This local admin panel shows the entire fleet for the current `partner_key`: nodes, modems, observed egress IP, traffic by modem, active clients, recent commands, and stable snapshot refresh from the main server.": "Este panel local muestra toda la flota del `partner_key` actual: nodos, módems, IP de salida, tráfico por módem, clientes activos, comandos recientes y una instantánea estable del servidor principal.",
    "Language": "Idioma", "Partner Key": "Clave de socio", "Main Server": "Servidor principal", "Refresh Mode": "Modo de actualización", "Last snapshot": "Última instantánea",
    "Nodes": "Nodos", "Modems": "Módems", "Clients": "Clientes", "Sessions": "Sesiones", "Traffic In": "Tráfico entrante", "Traffic Out": "Tráfico saliente", "Balance": "Saldo",
    "Currently online, degraded/offline:": "En línea actualmente, degradados/offline:", "Ready modems currently in the pool.": "Módems listos actualmente en el pool.", "Active leases through the main server for this partner fleet.": "Asignaciones activas a través del servidor principal.", "Aggregate load across all partner modems.": "Carga agregada en todos los módems.", "Inbound traffic from aggregated heartbeat data.": "Tráfico entrante desde heartbeats agregados.", "Daily accrual balance for this partner.": "Saldo diario acumulado para este socio.", "snapshot synced": "instantánea sincronizada", "refresh...": "actualizando...", "Refresh": "Actualizar",
    "Commands": "Comandos", "Realtime": "Tiempo real", "Runbook": "Runbook", "All partner nodes": "Todos los nodos del socio", "Operational snapshot per node: heartbeat, observed IP, traffic, ready pool, and status.": "Instantánea operativa por nodo: heartbeat, IP observada, tráfico, pool listo y estado.", "Node": "Nodo", "Status": "Estado", "Country": "País", "Observed IP": "IP observada", "Traffic": "Tráfico", "Heartbeat": "Heartbeat", "No nodes have been registered yet.": "Aún no hay nodos registrados.",
    "Modem fleet": "Flota de módems", "Observed egress IP, node-local modem number, firmware baseline, SIM ICCID, and package usage.": "IP de salida, número local del módem, firmware, ICCID SIM y uso del paquete.", "Scope": "Alcance", "This node only": "Solo este nodo", "All nodes": "Todos los nodos", "Node / Modem": "Nodo / Módem", "SIM": "SIM", "Operator": "Operador", "Tech": "Tecnología", "Signal": "Señal", "Plan": "Plan", "Action": "Acción", "blocked for clients": "bloqueado para clientes", "eligible": "elegible", "usage source unavailable": "fuente de uso no disponible", "Unlimited / no limit": "Ilimitado / sin límite", "Quota exhausted": "Cuota agotada", "No modems discovered on this node yet.": "Aún no hay módems en este nodo.", "No modems have been discovered yet.": "Aún no se han descubierto módems.",
    "Provisioning registry": "Registro de provisión", "Every modem gets a stable number by IMEI, so you can label the hardware and keep tracking it after moving to another USB port.": "Cada módem recibe un número estable por IMEI para etiquetarlo y seguirlo al moverlo de puerto USB.", "Clear node memory": "Borrar memoria del nodo", "Clearing...": "Borrando...", "Mark ready": "Marcar listo", "Needs flash": "Necesita flasheo", "Flash now": "Flashear ahora", "No provisioned modems yet. Plug them one by one to assign a stable modem number.": "Aún no hay módems provisionados. Conéctalos uno por uno para asignar un número estable.",
    "SIM package controls": "Controles de paquete SIM", "Per-modem traffic package, SIM health status, auto reset day, and manual reset of the current billing cycle.": "Paquete de tráfico por módem, salud SIM, día de reinicio y reinicio manual del ciclo actual.", "Plan": "Plan", "Limit GB": "Límite GB", "Cycle": "Ciclo", "Reset day": "Día de reinicio", "Notes": "Notas", "Metered": "Medido", "Unlimited": "Ilimitado", "Day of month": "Día del mes", "Rolling 30 days": "30 días móviles", "Save": "Guardar", "Saving...": "Guardando...", "Manual reset": "Reinicio manual", "Verify SIM": "Verificar SIM",
    "Fleet summary": "Resumen de flota", "Health, speed, local proxy diagnostics, and flash controls.": "Salud, velocidad, diagnóstico proxy local y controles de flasheo.", "Ready modems": "Módems listos", "Month accrual": "Acumulado mensual", "Last heartbeat": "Último heartbeat", "Important check": "Comprobación importante", "Auto-flash": "Auto-flash", "Node update": "Actualización del nodo", "Update node": "Actualizar nodo", "Local modem speed test": "Prueba local de velocidad", "Run test": "Ejecutar prueba", "Testing...": "Probando...", "Service": "Servicio", "Custom URL": "URL personalizada", "Download": "Descarga", "Transferred": "Transferido", "Duration": "Duración", "Remote IP": "IP remota", "URL": "URL",
    "Command center": "Centro de comandos", "Send commands to the selected node or modem without opening the main admin panel.": "Envía comandos al nodo o módem seleccionado sin abrir el panel principal.", "Target node": "Nodo destino", "Target modem": "Módem destino", "Command": "Comando", "Timeout, sec": "Timeout, seg", "Extra JSON params": "Parámetros JSON extra", "Queue command": "Encolar comando", "Reset JSON": "Restablecer JSON", "Quick actions": "Acciones rápidas", "Most common operations for day-to-day support.": "Operaciones comunes para soporte diario.", "Self-check": "Autodiagnóstico", "Reconcile config": "Reconciliar config", "Rotate IP": "Rotar IP", "Restart proxy": "Reiniciar proxy", "Self-update": "Autoactualizar",
    "Live event feed": "Eventos en vivo", "Last command results": "Últimos resultados", "No realtime events have been received yet.": "Aún no se recibieron eventos en tiempo real.", "No command results yet.": "Aún no hay resultados.", "Partner runbook": "Runbook del socio", "Flashing modem": "Flasheando módem", "Selected modem": "Módem seleccionado", "Close": "Cerrar"
  },
  zh_cn: {
    "Partner Fleet Console": "合作伙伴节点控制台", "Partner fleet console for all assigned nodes": "所有已分配节点的合作伙伴控制台", "Language": "语言", "Partner Key": "合作伙伴密钥", "Main Server": "主服务器", "Refresh Mode": "刷新模式", "Last snapshot": "最新快照",
    "Nodes": "节点", "Modems": "调制解调器", "Clients": "客户端", "Sessions": "会话", "Traffic In": "入站流量", "Traffic Out": "出站流量", "Balance": "余额", "Refresh": "刷新", "snapshot synced": "快照已同步", "refresh...": "刷新中...",
    "Commands": "命令", "Realtime": "实时", "Runbook": "运行手册", "All partner nodes": "所有合作伙伴节点", "Node": "节点", "Status": "状态", "Country": "国家", "Observed IP": "观察到的 IP", "Traffic": "流量", "Heartbeat": "心跳", "No nodes have been registered yet.": "尚未注册节点。",
    "Modem fleet": "调制解调器群组", "Scope": "范围", "This node only": "仅此节点", "All nodes": "所有节点", "Node / Modem": "节点 / 调制解调器", "SIM": "SIM 卡", "Operator": "运营商", "Tech": "制式", "Signal": "信号", "Plan": "套餐", "Action": "操作", "blocked for clients": "已对客户端禁用", "eligible": "可用", "usage source unavailable": "流量来源不可用", "Quota exhausted": "配额已用尽",
    "Provisioning registry": "配置注册表", "Clear node memory": "清除节点记忆", "Clearing...": "清除中...", "Mark ready": "标记为就绪", "Needs flash": "需要刷机", "Flash now": "立即刷机", "SIM package controls": "SIM 套餐控制", "Limit GB": "GB 限额", "Cycle": "周期", "Reset day": "重置日", "Notes": "备注", "Metered": "计量", "Unlimited": "不限量", "Day of month": "每月日期", "Rolling 30 days": "滚动 30 天", "Save": "保存", "Manual reset": "手动重置", "Verify SIM": "验证 SIM",
    "Fleet summary": "群组摘要", "Ready modems": "就绪调制解调器", "Month accrual": "本月累计", "Last heartbeat": "最后心跳", "Important check": "重要检查", "Auto-flash": "自动刷机", "Node update": "节点更新", "Update node": "更新节点", "Local modem speed test": "本地调制解调器测速", "Run test": "运行测试", "Service": "服务", "Custom URL": "自定义 URL", "Download": "下载", "Transferred": "已传输", "Duration": "耗时", "Remote IP": "远端 IP",
    "Command center": "命令中心", "Target node": "目标节点", "Target modem": "目标调制解调器", "Command": "命令", "Timeout, sec": "超时（秒）", "Extra JSON params": "额外 JSON 参数", "Queue command": "加入命令队列", "Reset JSON": "重置 JSON", "Quick actions": "快捷操作", "Self-check": "自检", "Reconcile config": "同步配置", "Rotate IP": "轮换 IP", "Restart proxy": "重启代理", "Self-update": "自更新",
    "Live event feed": "实时事件", "Last command results": "最近命令结果", "Partner runbook": "合作伙伴运行手册", "Flashing modem": "正在刷机", "Selected modem": "所选调制解调器", "Close": "关闭"
  },
  ar: {
    "Partner Fleet Console": "لوحة أسطول الشريك", "Partner fleet console for all assigned nodes": "لوحة أسطول الشريك لكل العقد المخصصة", "Language": "اللغة", "Partner Key": "مفتاح الشريك", "Main Server": "الخادم الرئيسي", "Refresh Mode": "وضع التحديث", "Last snapshot": "آخر لقطة",
    "Nodes": "العقد", "Modems": "المودمات", "Clients": "العملاء", "Sessions": "الجلسات", "Traffic In": "المرور الداخل", "Traffic Out": "المرور الخارج", "Balance": "الرصيد", "Refresh": "تحديث", "snapshot synced": "تمت مزامنة اللقطة", "refresh...": "جار التحديث...",
    "Commands": "الأوامر", "Realtime": "مباشر", "Runbook": "دليل التشغيل", "All partner nodes": "كل عقد الشريك", "Node": "العقدة", "Status": "الحالة", "Country": "الدولة", "Observed IP": "IP المرصود", "Traffic": "المرور", "Heartbeat": "نبضة", "No nodes have been registered yet.": "لم يتم تسجيل أي عقد بعد.",
    "Modem fleet": "أسطول المودمات", "Scope": "النطاق", "This node only": "هذه العقدة فقط", "All nodes": "كل العقد", "Node / Modem": "العقدة / المودم", "SIM": "الشريحة", "Operator": "المشغل", "Tech": "التقنية", "Signal": "الإشارة", "Plan": "الخطة", "Action": "الإجراء", "blocked for clients": "محظور للعملاء", "eligible": "متاح", "usage source unavailable": "مصدر الاستخدام غير متاح", "Quota exhausted": "انتهت الحصة",
    "Provisioning registry": "سجل التجهيز", "Clear node memory": "مسح ذاكرة العقدة", "Clearing...": "جار المسح...", "Mark ready": "تعيين كجاهز", "Needs flash": "يحتاج تفليش", "Flash now": "فلّش الآن", "SIM package controls": "إعدادات باقة الشريحة", "Limit GB": "الحد GB", "Cycle": "الدورة", "Reset day": "يوم التصفير", "Notes": "ملاحظات", "Metered": "محدود", "Unlimited": "غير محدود", "Day of month": "يوم من الشهر", "Rolling 30 days": "30 يوم متحركة", "Save": "حفظ", "Manual reset": "تصفير يدوي", "Verify SIM": "تحقق من الشريحة",
    "Fleet summary": "ملخص الأسطول", "Ready modems": "مودمات جاهزة", "Month accrual": "تراكم الشهر", "Last heartbeat": "آخر نبضة", "Important check": "فحص مهم", "Auto-flash": "تفليش تلقائي", "Node update": "تحديث العقدة", "Update node": "حدّث العقدة", "Local modem speed test": "اختبار سرعة المودم المحلي", "Run test": "تشغيل الاختبار", "Service": "الخدمة", "Custom URL": "رابط مخصص", "Download": "تنزيل", "Transferred": "تم النقل", "Duration": "المدة", "Remote IP": "IP البعيد",
    "Command center": "مركز الأوامر", "Target node": "العقدة الهدف", "Target modem": "المودم الهدف", "Command": "الأمر", "Timeout, sec": "المهلة، ثوان", "Extra JSON params": "معاملات JSON إضافية", "Queue command": "إضافة الأمر", "Reset JSON": "إعادة ضبط JSON", "Quick actions": "إجراءات سريعة", "Self-check": "فحص ذاتي", "Reconcile config": "مزامنة الإعدادات", "Rotate IP": "تغيير IP", "Restart proxy": "إعادة تشغيل البروكسي", "Self-update": "تحديث ذاتي",
    "Live event feed": "الأحداث المباشرة", "Last command results": "آخر نتائج الأوامر", "Partner runbook": "دليل الشريك", "Flashing modem": "تفليش المودم", "Selected modem": "المودم المحدد", "Close": "إغلاق"
  },
  fr: {
    "Partner Fleet Console": "Console de flotte partenaire", "Partner fleet console for all assigned nodes": "Console de flotte pour tous les nœuds assignés", "Language": "Langue", "Partner Key": "Clé partenaire", "Main Server": "Serveur principal", "Refresh Mode": "Mode d’actualisation", "Last snapshot": "Dernier instantané",
    "Nodes": "Nœuds", "Modems": "Modems", "Clients": "Clients", "Sessions": "Sessions", "Traffic In": "Trafic entrant", "Traffic Out": "Trafic sortant", "Balance": "Solde", "Refresh": "Actualiser", "snapshot synced": "instantané synchronisé", "refresh...": "actualisation...",
    "Commands": "Commandes", "Realtime": "Temps réel", "Runbook": "Runbook", "All partner nodes": "Tous les nœuds partenaires", "Node": "Nœud", "Status": "État", "Country": "Pays", "Observed IP": "IP observée", "Traffic": "Trafic", "Heartbeat": "Heartbeat",
    "Modem fleet": "Flotte de modems", "Scope": "Portée", "This node only": "Ce nœud uniquement", "All nodes": "Tous les nœuds", "Node / Modem": "Nœud / Modem", "SIM": "SIM", "Operator": "Opérateur", "Tech": "Tech", "Signal": "Signal", "Plan": "Forfait", "Action": "Action", "blocked for clients": "bloqué pour les clients", "eligible": "éligible", "usage source unavailable": "source d’usage indisponible",
    "Provisioning registry": "Registre de provisionnement", "Clear node memory": "Effacer la mémoire du nœud", "Mark ready": "Marquer prêt", "Needs flash": "Flash requis", "Flash now": "Flasher", "SIM package controls": "Contrôles du forfait SIM", "Limit GB": "Limite GB", "Cycle": "Cycle", "Reset day": "Jour de remise à zéro", "Notes": "Notes", "Metered": "Mesuré", "Unlimited": "Illimité", "Save": "Enregistrer", "Manual reset": "Réinitialisation manuelle", "Verify SIM": "Vérifier SIM",
    "Fleet summary": "Résumé de la flotte", "Ready modems": "Modems prêts", "Month accrual": "Cumul mensuel", "Last heartbeat": "Dernier heartbeat", "Important check": "Vérification importante", "Auto-flash": "Flash auto", "Node update": "Mise à jour du nœud", "Update node": "Mettre à jour", "Local modem speed test": "Test de vitesse local", "Run test": "Lancer le test", "Service": "Service", "Custom URL": "URL personnalisée", "Download": "Téléchargement", "Transferred": "Transféré", "Duration": "Durée", "Remote IP": "IP distante",
    "Command center": "Centre de commandes", "Target node": "Nœud cible", "Target modem": "Modem cible", "Command": "Commande", "Timeout, sec": "Timeout, sec", "Extra JSON params": "Paramètres JSON", "Queue command": "Mettre en file", "Reset JSON": "Réinitialiser JSON", "Quick actions": "Actions rapides", "Live event feed": "Flux d’événements", "Last command results": "Derniers résultats", "Partner runbook": "Runbook partenaire", "Flashing modem": "Flash du modem", "Close": "Fermer"
  },
  de: {
    "Partner Fleet Console": "Partner-Flottenkonsole", "Partner fleet console for all assigned nodes": "Flottenkonsole für alle zugewiesenen Nodes", "Language": "Sprache", "Partner Key": "Partner-Schlüssel", "Main Server": "Hauptserver", "Refresh Mode": "Aktualisierungsmodus", "Last snapshot": "Letzter Snapshot",
    "Nodes": "Nodes", "Modems": "Modems", "Clients": "Clients", "Sessions": "Sitzungen", "Traffic In": "Traffic rein", "Traffic Out": "Traffic raus", "Balance": "Guthaben", "Refresh": "Aktualisieren", "snapshot synced": "Snapshot synchronisiert", "refresh...": "aktualisiere...",
    "Commands": "Befehle", "Realtime": "Echtzeit", "Runbook": "Runbook", "All partner nodes": "Alle Partner-Nodes", "Node": "Node", "Status": "Status", "Country": "Land", "Observed IP": "Beobachtete IP", "Traffic": "Traffic", "Heartbeat": "Heartbeat",
    "Modem fleet": "Modem-Flotte", "Scope": "Bereich", "This node only": "Nur dieser Node", "All nodes": "Alle Nodes", "Node / Modem": "Node / Modem", "SIM": "SIM", "Operator": "Anbieter", "Tech": "Technik", "Signal": "Signal", "Plan": "Tarif", "Action": "Aktion", "blocked for clients": "für Clients gesperrt", "eligible": "verfügbar", "usage source unavailable": "Nutzungsquelle nicht verfügbar",
    "Provisioning registry": "Provisioning-Register", "Clear node memory": "Node-Speicher löschen", "Mark ready": "Als bereit markieren", "Needs flash": "Flash nötig", "Flash now": "Jetzt flashen", "SIM package controls": "SIM-Tarifsteuerung", "Limit GB": "Limit GB", "Cycle": "Zyklus", "Reset day": "Reset-Tag", "Notes": "Notizen", "Metered": "Begrenzt", "Unlimited": "Unbegrenzt", "Save": "Speichern", "Manual reset": "Manueller Reset", "Verify SIM": "SIM prüfen",
    "Fleet summary": "Flottenübersicht", "Ready modems": "Bereite Modems", "Month accrual": "Monatsgutschrift", "Last heartbeat": "Letzter Heartbeat", "Important check": "Wichtiger Check", "Auto-flash": "Auto-Flash", "Node update": "Node-Update", "Update node": "Node aktualisieren", "Local modem speed test": "Lokaler Modem-Speedtest", "Run test": "Test starten", "Service": "Dienst", "Custom URL": "Eigene URL", "Download": "Download", "Transferred": "Übertragen", "Duration": "Dauer", "Remote IP": "Remote-IP",
    "Command center": "Befehlszentrum", "Target node": "Ziel-Node", "Target modem": "Ziel-Modem", "Command": "Befehl", "Timeout, sec": "Timeout, Sek.", "Extra JSON params": "Extra JSON-Parameter", "Queue command": "Befehl einreihen", "Reset JSON": "JSON zurücksetzen", "Quick actions": "Schnellaktionen", "Live event feed": "Live-Ereignisse", "Last command results": "Letzte Befehle", "Partner runbook": "Partner-Runbook", "Flashing modem": "Modem wird geflasht", "Close": "Schließen"
  },
  tr: {
    "Partner Fleet Console": "İş Ortağı Filo Konsolu", "Partner fleet console for all assigned nodes": "Atanmış tüm node’lar için filo konsolu", "Language": "Dil", "Partner Key": "Partner anahtarı", "Main Server": "Ana sunucu", "Refresh Mode": "Yenileme modu", "Last snapshot": "Son anlık görüntü",
    "Nodes": "Node’lar", "Modems": "Modemler", "Clients": "İstemciler", "Sessions": "Oturumlar", "Traffic In": "Gelen trafik", "Traffic Out": "Giden trafik", "Balance": "Bakiye", "Refresh": "Yenile",
    "Commands": "Komutlar", "Realtime": "Canlı", "Runbook": "Runbook", "All partner nodes": "Tüm partner node’ları", "Node": "Node", "Status": "Durum", "Country": "Ülke", "Observed IP": "Görülen IP", "Traffic": "Trafik", "Modem fleet": "Modem filosu", "Scope": "Kapsam", "This node only": "Sadece bu node", "All nodes": "Tüm node’lar", "Signal": "Sinyal", "Plan": "Paket", "Action": "Aksiyon", "blocked for clients": "istemcilere kapalı", "eligible": "uygun", "usage source unavailable": "kullanım kaynağı yok",
    "Provisioning registry": "Kurulum kaydı", "Clear node memory": "Node hafızasını temizle", "Mark ready": "Hazır işaretle", "Needs flash": "Flash gerekiyor", "Flash now": "Şimdi flashla", "SIM package controls": "SIM paket kontrolleri", "Limit GB": "Limit GB", "Cycle": "Döngü", "Reset day": "Sıfırlama günü", "Save": "Kaydet", "Manual reset": "Manuel sıfırla", "Verify SIM": "SIM doğrula",
    "Fleet summary": "Filo özeti", "Ready modems": "Hazır modemler", "Node update": "Node güncelleme", "Update node": "Node’u güncelle", "Local modem speed test": "Yerel modem hız testi", "Run test": "Testi çalıştır", "Command center": "Komut merkezi", "Quick actions": "Hızlı işlemler", "Live event feed": "Canlı olaylar", "Partner runbook": "Partner runbook", "Flashing modem": "Modem flashlanıyor", "Close": "Kapat"
  },
  it: {
    "Partner Fleet Console": "Console flotta partner", "Partner fleet console for all assigned nodes": "Console flotta per tutti i nodi assegnati", "Language": "Lingua", "Partner Key": "Chiave partner", "Main Server": "Server principale", "Nodes": "Nodi", "Modems": "Modem", "Clients": "Client", "Sessions": "Sessioni", "Traffic In": "Traffico in ingresso", "Traffic Out": "Traffico in uscita", "Balance": "Saldo", "Refresh": "Aggiorna",
    "Commands": "Comandi", "Realtime": "Tempo reale", "Runbook": "Runbook", "All partner nodes": "Tutti i nodi partner", "Node": "Nodo", "Status": "Stato", "Country": "Paese", "Observed IP": "IP osservato", "Traffic": "Traffico", "Modem fleet": "Flotta modem", "Scope": "Ambito", "This node only": "Solo questo nodo", "All nodes": "Tutti i nodi", "Signal": "Segnale", "Plan": "Piano", "Action": "Azione", "blocked for clients": "bloccato per i client", "eligible": "idoneo", "usage source unavailable": "fonte uso non disponibile",
    "Provisioning registry": "Registro provisioning", "Clear node memory": "Cancella memoria nodo", "Mark ready": "Segna pronto", "Needs flash": "Richiede flash", "Flash now": "Flash ora", "SIM package controls": "Controlli pacchetto SIM", "Limit GB": "Limite GB", "Cycle": "Ciclo", "Reset day": "Giorno reset", "Save": "Salva", "Manual reset": "Reset manuale", "Verify SIM": "Verifica SIM", "Fleet summary": "Riepilogo flotta", "Ready modems": "Modem pronti", "Node update": "Aggiornamento nodo", "Update node": "Aggiorna nodo", "Local modem speed test": "Test velocità modem locale", "Run test": "Esegui test", "Command center": "Centro comandi", "Quick actions": "Azioni rapide", "Flashing modem": "Flash modem", "Close": "Chiudi"
  },
  pl: {
    "Partner Fleet Console": "Konsola floty partnera", "Partner fleet console for all assigned nodes": "Konsola floty dla wszystkich przypisanych węzłów", "Language": "Język", "Partner Key": "Klucz partnera", "Main Server": "Serwer główny", "Nodes": "Węzły", "Modems": "Modemy", "Clients": "Klienci", "Sessions": "Sesje", "Traffic In": "Ruch przychodzący", "Traffic Out": "Ruch wychodzący", "Balance": "Saldo", "Refresh": "Odśwież",
    "Commands": "Polecenia", "Realtime": "Na żywo", "Runbook": "Runbook", "All partner nodes": "Wszystkie węzły partnera", "Node": "Węzeł", "Status": "Status", "Country": "Kraj", "Observed IP": "Zaobserwowane IP", "Traffic": "Ruch", "Modem fleet": "Flota modemów", "Scope": "Zakres", "This node only": "Tylko ten węzeł", "All nodes": "Wszystkie węzły", "Signal": "Sygnał", "Plan": "Plan", "Action": "Akcja", "blocked for clients": "zablokowany dla klientów", "eligible": "dostępny", "usage source unavailable": "źródło użycia niedostępne",
    "Provisioning registry": "Rejestr provisioningu", "Clear node memory": "Wyczyść pamięć węzła", "Mark ready": "Oznacz jako gotowy", "Needs flash": "Wymaga flashowania", "Flash now": "Flashuj teraz", "SIM package controls": "Kontrola pakietu SIM", "Limit GB": "Limit GB", "Cycle": "Cykl", "Reset day": "Dzień resetu", "Save": "Zapisz", "Manual reset": "Reset ręczny", "Verify SIM": "Sprawdź SIM", "Fleet summary": "Podsumowanie floty", "Ready modems": "Gotowe modemy", "Node update": "Aktualizacja węzła", "Update node": "Aktualizuj węzeł", "Run test": "Uruchom test", "Command center": "Centrum poleceń", "Quick actions": "Szybkie akcje", "Close": "Zamknij"
  },
  vi: {
    "Partner Fleet Console": "Bảng điều khiển đội node đối tác", "Partner fleet console for all assigned nodes": "Bảng điều khiển cho toàn bộ node được gán", "Language": "Ngôn ngữ", "Partner Key": "Khóa đối tác", "Main Server": "Máy chủ chính", "Nodes": "Node", "Modems": "Modem", "Clients": "Client", "Sessions": "Phiên", "Traffic In": "Lưu lượng vào", "Traffic Out": "Lưu lượng ra", "Balance": "Số dư", "Refresh": "Làm mới",
    "Commands": "Lệnh", "Realtime": "Thời gian thực", "Runbook": "Runbook", "All partner nodes": "Tất cả node đối tác", "Node": "Node", "Status": "Trạng thái", "Country": "Quốc gia", "Observed IP": "IP quan sát", "Traffic": "Lưu lượng", "Modem fleet": "Đội modem", "Scope": "Phạm vi", "This node only": "Chỉ node này", "All nodes": "Tất cả node", "Signal": "Tín hiệu", "Plan": "Gói", "Action": "Thao tác", "blocked for clients": "chặn cho client", "eligible": "khả dụng", "usage source unavailable": "không có nguồn usage",
    "Provisioning registry": "Registry cấu hình", "Clear node memory": "Xóa bộ nhớ node", "Mark ready": "Đánh dấu sẵn sàng", "Needs flash": "Cần flash", "Flash now": "Flash ngay", "SIM package controls": "Điều khiển gói SIM", "Limit GB": "Giới hạn GB", "Cycle": "Chu kỳ", "Reset day": "Ngày reset", "Save": "Lưu", "Manual reset": "Reset thủ công", "Verify SIM": "Xác minh SIM", "Fleet summary": "Tóm tắt đội", "Ready modems": "Modem sẵn sàng", "Node update": "Cập nhật node", "Update node": "Cập nhật node", "Run test": "Chạy test", "Command center": "Trung tâm lệnh", "Quick actions": "Thao tác nhanh", "Close": "Đóng"
  },
  ja: {
    "Partner Fleet Console": "パートナーフリートコンソール", "Partner fleet console for all assigned nodes": "割り当て済みノードのフリートコンソール", "Language": "言語", "Partner Key": "パートナーキー", "Main Server": "メインサーバー", "Nodes": "ノード", "Modems": "モデム", "Clients": "クライアント", "Sessions": "セッション", "Traffic In": "受信トラフィック", "Traffic Out": "送信トラフィック", "Balance": "残高", "Refresh": "更新",
    "Commands": "コマンド", "Realtime": "リアルタイム", "Runbook": "ランブック", "All partner nodes": "すべてのパートナーノード", "Node": "ノード", "Status": "状態", "Country": "国", "Observed IP": "観測 IP", "Traffic": "トラフィック", "Modem fleet": "モデム一覧", "Scope": "範囲", "This node only": "このノードのみ", "All nodes": "全ノード", "Signal": "信号", "Plan": "プラン", "Action": "操作", "blocked for clients": "クライアント不可", "eligible": "利用可能", "usage source unavailable": "使用量ソースなし",
    "Provisioning registry": "プロビジョニング登録", "Clear node memory": "ノード記憶を消去", "Mark ready": "準備完了にする", "Needs flash": "フラッシュ必要", "Flash now": "今すぐフラッシュ", "SIM package controls": "SIM パッケージ設定", "Limit GB": "上限 GB", "Cycle": "周期", "Reset day": "リセット日", "Save": "保存", "Manual reset": "手動リセット", "Verify SIM": "SIM 確認", "Fleet summary": "フリート概要", "Ready modems": "準備済みモデム", "Node update": "ノード更新", "Update node": "ノードを更新", "Run test": "テスト実行", "Command center": "コマンドセンター", "Quick actions": "クイック操作", "Close": "閉じる"
  },
  pt_br: {
    "Partner Fleet Console": "Console da frota do parceiro", "Partner fleet console for all assigned nodes": "Console da frota para todos os nós atribuídos", "Language": "Idioma", "Partner Key": "Chave do parceiro", "Main Server": "Servidor principal", "Nodes": "Nós", "Modems": "Modems", "Clients": "Clientes", "Sessions": "Sessões", "Traffic In": "Tráfego de entrada", "Traffic Out": "Tráfego de saída", "Balance": "Saldo", "Refresh": "Atualizar",
    "Commands": "Comandos", "Realtime": "Tempo real", "Runbook": "Runbook", "All partner nodes": "Todos os nós do parceiro", "Node": "Nó", "Status": "Status", "Country": "País", "Observed IP": "IP observado", "Traffic": "Tráfego", "Modem fleet": "Frota de modems", "Scope": "Escopo", "This node only": "Somente este nó", "All nodes": "Todos os nós", "Signal": "Sinal", "Plan": "Plano", "Action": "Ação", "blocked for clients": "bloqueado para clientes", "eligible": "elegível", "usage source unavailable": "fonte de uso indisponível",
    "Provisioning registry": "Registro de provisionamento", "Clear node memory": "Limpar memória do nó", "Mark ready": "Marcar pronto", "Needs flash": "Precisa de flash", "Flash now": "Fazer flash agora", "SIM package controls": "Controles do pacote SIM", "Limit GB": "Limite GB", "Cycle": "Ciclo", "Reset day": "Dia de reset", "Save": "Salvar", "Manual reset": "Reset manual", "Verify SIM": "Verificar SIM", "Fleet summary": "Resumo da frota", "Ready modems": "Modems prontos", "Node update": "Atualização do nó", "Update node": "Atualizar nó", "Run test": "Executar teste", "Command center": "Central de comandos", "Quick actions": "Ações rápidas", "Close": "Fechar"
  },
}

export function htmlLangForLocale(locale) {
  return languageOptions.find((item) => item.code === locale)?.htmlLang || "en-GB"
}

export function isRTLLocale(locale) {
  return Boolean(languageOptions.find((item) => item.code === locale)?.rtl)
}

export function translateText(locale, text) {
  const normalized = String(text || "").replace(/\s+/g, " ").trim()
  if (!normalized || locale === "en_gb" || locale === "en_us") return normalized
  return packs[locale]?.[normalized] || normalized
}
