#!/usr/bin/env bash
###############################################################################
# Setup node-agent configuration
# Creates /etc/partner-node/config.yaml
###############################################################################

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

CONFIG_DIR="${CONFIG_DIR:-/etc/partner-node}"
DATA_DIR="${DATA_DIR:-/var/lib/partner-node}"
LOG_DIR="${LOG_DIR:-/var/log/partner-node}"
MAIN_SERVER="${MAIN_SERVER:-}"
COUNTRY="${COUNTRY:-US}"
HILINK_ENABLED="${HILINK_ENABLED:-true}"
HILINK_BASE_URL="${HILINK_BASE_URL:-http://192.168.13.1}"
HILINK_TIMEOUT="${HILINK_TIMEOUT:-15s}"

setup_config() {
  require_root

  if [[ -z "$MAIN_SERVER" ]]; then
    log_err "MAIN_SERVER is required"
    return 1
  fi

  log_info "Setting up configuration..."

  # Create directories
  mkdir -p "$CONFIG_DIR" "$DATA_DIR" "$LOG_DIR"
  chmod 755 "$CONFIG_DIR" "$DATA_DIR" "$LOG_DIR"

  # Create config file
  log_info "Creating $CONFIG_DIR/config.yaml"
  cat > "$CONFIG_DIR/config.yaml" <<EOF
# Partner Node Configuration
# Generated by installer on $(date)

server:
  main_server: "$MAIN_SERVER"
  heartbeat_interval: "10s"
  request_timeout: "30s"

node:
  country: "$COUNTRY"
  id: ""  # Will be populated after bootstrap
  token: ""  # Will be populated after bootstrap

modem:
  hilink:
    enabled: $HILINK_ENABLED
    base_url: "$HILINK_BASE_URL"
    timeout: "$HILINK_TIMEOUT"

proxy:
  binary_path: "/usr/bin/3proxy"
  config_path: "/etc/3proxy/3proxy.conf"
  base_port: 31000

logging:
  level: "info"
  dev_mode: false

state:
  file: "$DATA_DIR/state.json"
EOF

  chmod 644 "$CONFIG_DIR/config.yaml"
  log_info "Configuration created"

  log_info "✅ Config setup complete"
}

# Run if sourced directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  setup_config "$@"
fi
