#!/usr/bin/env bash
###############################################################################
# Setup AmneziaWG tooling for NAT-safe relay transport.
# Userspace amneziawg-go is preferred when available; kernel tooling is optional.
###############################################################################

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

AMNEZIAWG_GO_URL="${AMNEZIAWG_GO_URL:-}"
AMNEZIAWG_TOOLS_URL="${AMNEZIAWG_TOOLS_URL:-}"
AMNEZIAWG_GO_PATH="${AMNEZIAWG_GO_PATH:-/usr/local/bin/amneziawg-go}"
AWG_PATH="${AWG_PATH:-/usr/local/bin/awg}"
AWG_QUICK_PATH="${AWG_QUICK_PATH:-/usr/local/bin/awg-quick}"
AMNEZIAWG_ENV_PATH="${AMNEZIAWG_ENV_PATH:-/etc/partner-node/amneziawg.env}"

detect_arch_suffix() {
  case "$(uname -m)" in
    x86_64|amd64) echo "linux-amd64" ;;
    aarch64|arm64) echo "linux-arm64" ;;
    armv7l|armv7*) echo "linux-armv7" ;;
    *) echo "linux-amd64" ;;
  esac
}

install_base_tools() {
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -y || true
    apt-get install -y wireguard-tools iproute2 ca-certificates curl kmod || true
    return
  fi
  if command -v dnf >/dev/null 2>&1; then
    dnf install -y wireguard-tools iproute ca-certificates curl || true
    return
  fi
  if command -v yum >/dev/null 2>&1; then
    yum install -y wireguard-tools iproute ca-certificates curl || true
  fi
}

install_userspace_awg() {
  local arch asset_base
  arch="$(detect_arch_suffix)"
  asset_base="${ASSET_BASE_URL:-}"
  if [[ -z "$asset_base" && -n "${MAIN_SERVER:-}" ]]; then
    asset_base="${MAIN_SERVER%/}/downloads/partner-node"
  fi
  if [[ -z "$AMNEZIAWG_GO_URL" && -n "$asset_base" ]]; then
    AMNEZIAWG_GO_URL="${asset_base}/amneziawg-go-${arch}"
  fi
  if [[ -z "$AMNEZIAWG_TOOLS_URL" && -n "$asset_base" ]]; then
    AMNEZIAWG_TOOLS_URL="${asset_base}/amneziawg-tools-${arch}.tar.gz"
  fi

  if command -v amneziawg-go >/dev/null 2>&1 || [[ -x "$AMNEZIAWG_GO_PATH" ]]; then
    log_info "amneziawg-go already installed"
  elif [[ -n "$AMNEZIAWG_GO_URL" ]]; then
    local tmp
    tmp="$(mktemp)"
    log_info "Downloading amneziawg-go from $AMNEZIAWG_GO_URL"
    if curl -fsSL "$AMNEZIAWG_GO_URL" -o "$tmp"; then
      install -m 0755 "$tmp" "$AMNEZIAWG_GO_PATH"
      log_info "Installed amneziawg-go to $AMNEZIAWG_GO_PATH"
    else
      log_warn "Failed to download amneziawg-go; WSS fallback remains available"
    fi
    rm -f "$tmp"
  else
    log_warn "AMNEZIAWG_GO_URL is not set; skipping userspace amneziawg-go download"
  fi

  if command -v awg >/dev/null 2>&1 && command -v awg-quick >/dev/null 2>&1; then
    log_info "AmneziaWG tools already installed"
    return 0
  fi

  if [[ -n "$AMNEZIAWG_TOOLS_URL" ]]; then
    local tools_tmp tools_dir
    tools_tmp="$(mktemp)"
    tools_dir="$(mktemp -d)"
    log_info "Downloading AmneziaWG tools from $AMNEZIAWG_TOOLS_URL"
    if curl -fsSL "$AMNEZIAWG_TOOLS_URL" -o "$tools_tmp" && tar -xzf "$tools_tmp" -C "$tools_dir"; then
      if [[ -f "$tools_dir/awg" ]]; then
        install -m 0755 "$tools_dir/awg" "$AWG_PATH"
      fi
      if [[ -f "$tools_dir/awg-quick" ]]; then
        install -m 0755 "$tools_dir/awg-quick" "$AWG_QUICK_PATH"
      fi
      log_info "Installed AmneziaWG tools to /usr/local/bin"
    else
      log_warn "Failed to download AmneziaWG tools archive; wireguard-tools fallback remains available"
    fi
    rm -rf "$tools_tmp" "$tools_dir"
  else
    log_warn "AMNEZIAWG_TOOLS_URL is not set; using wireguard-tools fallback if available"
  fi
}

ensure_tun_device() {
  if [[ -e /dev/net/tun ]]; then
    return 0
  fi
  modprobe tun 2>/dev/null || true
  if [[ ! -e /dev/net/tun ]]; then
    mkdir -p /dev/net
    mknod /dev/net/tun c 10 200 2>/dev/null || true
    chmod 0666 /dev/net/tun 2>/dev/null || true
  fi
  if [[ -e /dev/net/tun ]]; then
    log_info "/dev/net/tun is available"
  else
    log_warn "/dev/net/tun is missing; AmneziaWG cannot start until TUN is available"
  fi
}

write_env_file() {
  mkdir -p "$(dirname "$AMNEZIAWG_ENV_PATH")"
  cat > "$AMNEZIAWG_ENV_PATH" <<EOF
# Generated by partner-node installer
AMNEZIAWG_GO_PATH="$AMNEZIAWG_GO_PATH"
AWG_PATH="$AWG_PATH"
AWG_QUICK_PATH="$AWG_QUICK_PATH"
AMNEZIAWG_INTERFACE="${AMNEZIAWG_INTERFACE:-awg0}"
AMNEZIAWG_PREFERRED_IMPL="${AMNEZIAWG_PREFERRED_IMPL:-userspace}"
EOF
  chmod 0644 "$AMNEZIAWG_ENV_PATH"
}

setup_amneziawg() {
  require_root
  log_info "Setting up AmneziaWG tooling..."
  install_base_tools
  ensure_tun_device
  install_userspace_awg
  mkdir -p /etc/amneziawg /var/lib/partner-node/amneziawg
  chmod 700 /etc/amneziawg /var/lib/partner-node/amneziawg
  write_env_file
  log_info "AmneziaWG tooling step complete"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  setup_amneziawg "$@"
fi
