#!/usr/bin/env bash
###############################################################################
# Setup AmneziaWG tooling for NAT-safe relay transport.
# Userspace amneziawg-go is preferred when available; kernel tooling is optional.
###############################################################################

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

AMNEZIAWG_GO_URL="${AMNEZIAWG_GO_URL:-}"
AMNEZIAWG_GO_PATH="${AMNEZIAWG_GO_PATH:-/usr/local/bin/amneziawg-go}"
AMNEZIAWG_ENV_PATH="${AMNEZIAWG_ENV_PATH:-/etc/partner-node/amneziawg.env}"

install_base_tools() {
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -y || true
    apt-get install -y wireguard-tools iproute2 ca-certificates curl || true
    return
  fi
  if command -v dnf >/dev/null 2>&1; then
    dnf install -y wireguard-tools iproute ca-certificates curl || true
    return
  fi
  if command -v yum >/dev/null 2>&1; then
    yum install -y wireguard-tools iproute ca-certificates curl || true
  fi
}

install_userspace_awg() {
  if command -v amneziawg-go >/dev/null 2>&1 || [[ -x "$AMNEZIAWG_GO_PATH" ]]; then
    log_info "amneziawg-go already installed"
    return 0
  fi

  if [[ -z "$AMNEZIAWG_GO_URL" ]]; then
    log_warn "AMNEZIAWG_GO_URL is not set; skipping userspace amneziawg-go download"
    log_warn "Node will still use WSS fallback and can use kernel AmneziaWG if installed separately"
    return 0
  fi

  local tmp
  tmp="$(mktemp)"
  log_info "Downloading amneziawg-go from $AMNEZIAWG_GO_URL"
  if curl -fsSL "$AMNEZIAWG_GO_URL" -o "$tmp"; then
    install -m 0755 "$tmp" "$AMNEZIAWG_GO_PATH"
    log_info "Installed amneziawg-go to $AMNEZIAWG_GO_PATH"
  else
    log_warn "Failed to download amneziawg-go; WSS fallback remains available"
  fi
  rm -f "$tmp"
}

write_env_file() {
  mkdir -p "$(dirname "$AMNEZIAWG_ENV_PATH")"
  cat > "$AMNEZIAWG_ENV_PATH" <<EOF
# Generated by partner-node installer
AMNEZIAWG_GO_PATH="$AMNEZIAWG_GO_PATH"
AMNEZIAWG_INTERFACE="${AMNEZIAWG_INTERFACE:-awg0}"
AMNEZIAWG_PREFERRED_IMPL="${AMNEZIAWG_PREFERRED_IMPL:-userspace}"
EOF
  chmod 0644 "$AMNEZIAWG_ENV_PATH"
}

setup_amneziawg() {
  require_root
  log_info "Setting up AmneziaWG tooling..."
  install_base_tools
  install_userspace_awg
  write_env_file
  log_info "AmneziaWG tooling step complete"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  setup_amneziawg "$@"
fi
