#!/usr/bin/env bash
###############################################################################
# Setup 3proxy SOCKS5 proxy
# Installs 3proxy package and ensures systemd uses partner-node config
###############################################################################

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

THREEPROXY_PACKAGE_URL="${THREEPROXY_PACKAGE_URL:-https://chatmod.warforgalaxy.com/downloads/partner-node/3proxy.deb}"

setup_3proxy() {
  require_root

  log_info "Setting up 3proxy..."

  if command_exists 3proxy; then
    log_info "3proxy is already installed"
    3proxy -v || true
  else
    local distro
    distro=$(get_distro)

    case "$distro" in
      debian|ubuntu)
        log_info "Downloading 3proxy package..."
        local temp_package="/tmp/3proxy.deb"
        download_file "$THREEPROXY_PACKAGE_URL" "$temp_package" || {
          log_err "Failed to download 3proxy"
          return 1
        }

        log_info "Installing 3proxy..."
        dpkg -i "$temp_package" || {
          log_warn "dpkg install failed, trying apt-get fix..."
          apt-get install -f -y || return 1
        }
        rm -f "$temp_package"
        ;;

      centos|rhel|fedora)
        log_warn "3proxy RPM not yet available, skipping installation"
        log_warn "Manual installation may be required"
        return 1
        ;;

      *)
        log_warn "3proxy installation not supported for distro: $distro"
        return 1
        ;;
    esac

    if command_exists 3proxy; then
      log_info "3proxy installed successfully"
      3proxy -v || true
    else
      log_err "3proxy installation verification failed"
      return 1
    fi
  fi

  mkdir -p /etc/3proxy
  chmod 755 /etc/3proxy

  cat > /etc/3proxy/3proxy.conf <<'EOF'
# 3proxy configuration
# This file is auto-generated by node-agent
# Manual changes will be overwritten

# Bind to all interfaces
internal 0.0.0.0 3128

# SOCKS5 server will be added by node-agent
# Placeholder for dynamic configuration

# Access control
allow *
EOF

  chmod 644 /etc/3proxy/3proxy.conf

  # Debian/Ubuntu packages start /etc/3proxy/3proxy.cfg by default.
  # partner-node renders /etc/3proxy/3proxy.conf, so we pin the unit to it.
  mkdir -p /etc/systemd/system/3proxy.service.d
  cat > /etc/systemd/system/3proxy.service.d/override.conf <<'EOF'
[Service]
Type=forking
PIDFile=/var/run/3proxy.pid
ExecStart=
ExecStart=/usr/bin/3proxy /etc/3proxy/3proxy.conf
ExecReload=
ExecReload=/bin/kill -SIGUSR1 $MAINPID
KillMode=control-group
EOF
  chmod 644 /etc/systemd/system/3proxy.service.d/override.conf
  systemctl daemon-reload

  log_info "3proxy setup complete"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  setup_3proxy "$@"
fi
