#!/usr/bin/env bash
###############################################################################
# Setup node-agent configuration
# Creates /etc/partner-node/config.yaml
###############################################################################

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

CONFIG_DIR="${CONFIG_DIR:-/etc/partner-node}"
DATA_DIR="${DATA_DIR:-/var/lib/partner-node}"
LOG_DIR="${LOG_DIR:-/var/log/partner-node}"
MAIN_SERVER="${MAIN_SERVER:-}"
COUNTRY="${COUNTRY:-US}"
HILINK_ENABLED="${HILINK_ENABLED:-true}"
HILINK_BASE_URL="${HILINK_BASE_URL:-}"
HILINK_TIMEOUT="${HILINK_TIMEOUT:-15s}"
SUPPORT_SSH_USER="${SUPPORT_SSH_USER:-}"

detect_support_user() {
  if [[ -n "$SUPPORT_SSH_USER" ]]; then
    echo "$SUPPORT_SSH_USER"
    return
  fi
  if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    echo "$SUDO_USER"
    return
  fi
  logname 2>/dev/null || true
}

setup_config() {
  require_root

  if [[ -z "$MAIN_SERVER" ]]; then
    log_err "MAIN_SERVER is required"
    return 1
  fi

  log_info "Setting up configuration..."
  SUPPORT_SSH_USER="$(detect_support_user)"

  # Create directories
  mkdir -p "$CONFIG_DIR" "$DATA_DIR" "$LOG_DIR"
  chmod 755 "$CONFIG_DIR" "$DATA_DIR" "$LOG_DIR"

  # Create config file
  log_info "Creating $CONFIG_DIR/config.yaml"
  cat > "$CONFIG_DIR/config.yaml" <<EOF
# Partner Node Configuration
# Generated by installer on $(date)

agent:
  country: "$COUNTRY"
  heartbeat_interval: "10s"
  health_check_interval: "30s"

api:
  partner_key: "$PARTNER_KEY"
  main_server: "$MAIN_SERVER"
  request_timeout: "30s"
  retry_max_attempts: 3
  retry_initial_delay: "1s"
  retry_max_delay: "60s"

node:
  id: ""  # Will be populated after bootstrap
  token: ""  # Will be populated after bootstrap

modem:
  discovery_interval: "30s"
  hilink:
    enabled: $HILINK_ENABLED
    base_url: "$HILINK_BASE_URL"
    timeout: "$HILINK_TIMEOUT"

proxy:
  binary_path: "/usr/bin/3proxy"
  config_path: "/etc/3proxy/3proxy.conf"
  base_port: 31000

logging:
  level: "info"
  format: "json"

state:
  file: "$DATA_DIR/state.json"

support:
  ssh_user: "$SUPPORT_SSH_USER"
EOF

  chmod 644 "$CONFIG_DIR/config.yaml"
  log_info "Configuration created"

  log_info "✅ Config setup complete"
}

# Run if sourced directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  setup_config "$@"
fi
